### PR TITLE
Fix: Crash on dragging map

### LINKED ISSUE #430: An error occurs when clicking randomly on "Rund um's Fahrrad" locations and dragging the map
Scenario:
- Choose the POI "Rund um's Fahrrad"
- Zoom to the scale of "100 m"
- Open the details of random "Rund um's Fahrrad" locations
- While keeping the details window open drag the map randomly 
- Suddenly the following error will appear
image
image
image
image

QA version:
 image: mfdz/opentripplanner:otp2-3bcf0f41606d3b70f681b2f355064f71d3ace246
 image: stadtnavi/digitransit-ui:fa8193fbace646e9f94132cda0732a9d8435c802
 image: stadtnavi/hsl-map-server:a563129166683c99bfdedb88f00bb9117afff726
 image: stadtnavi/fares-service:a9d1987be58d86b877699ede204ad537afd0bda1

### PR DESCRIPTION
**Pull request by andreashelms**
## Proposed Changes

  - Fixes crash on dragging map

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #430

### CODE REVIEW

File: app/component/map/MapWithTracking.js [hunk 1]
```diff
@@ -376,13 +376,21 @@ class MapWithTrackingStateHandler extends React.Component {
...
+              this.setState({ keepOnTracking: false });
+            }
           },
-          onMoveend: () => this.setState({ keepOnTracking: false }),
           onDragend: () => {
-            this.updateCurrentBounds();
-            this.setState({ humanIsScrolling: false });
+            if (this.isCanceled) {
+              this.updateCurrentBounds();
+              this.setState({ humanIsScrolling: false });
```
Comment (andreashelms) [inline app/component/map/MapWithTracking.js:392]: This caused the crash, because state was changed when the component was already unmounted. This condition here is quite dirty and there should be a better solution of avoiding this, so let me know if you have one.

Comment (leonardehrenfried) [reply app/component/map/MapWithTracking.js:392]: I don't have one. I will merge this in as is. If you have a better idea, we can change it later.
