### PR TITLE
fix(poi-layer): feature selectable below min zoom level

### LINKED ISSUE #879: POI features selectable even if not visible

### PR DESCRIPTION
**Pull request by andreashelms**
closes #879

### CODE REVIEW

File: app/component/map/tile-layer/PoiVectorTileLayer.js [hunk 1]
```diff
@@ -58,18 +58,18 @@ export default class PoiVectorTileLayer {
...
             })
-            .filter(Boolean);
+            .filter(feature => {
+              const poiLayer = getLayerByCode(
+                feature.properties.category3,
+                this.config,
+              );
+              return (
+                PoiVectorTileLayer.visibleCategories[poiLayer.code] &&
+                this.tile.coords.z >= poiLayer.properties.layer.min_zoom
```
Comment (hbruch) [inline app/component/map/tile-layer/PoiVectorTileLayer.js:70]: visibility z level may differ by category, what should be taken into account here, no?

Comment (andreashelms) [reply app/component/map/tile-layer/PoiVectorTileLayer.js:70]: `poiLayer` is a specific poi layer selected by category code. So `min_zoom` is already applied individually for each category.

**Review by hbruch — APPROVED** [review]
LGTM, thanks
