### PR TITLE
fix(itinerary-list): contains non transit entries

### LINKED ISSUE #845: Bug: Duration discrepancy in intermodal route (web)
**Description:**

In the "Bike+Public Transport" and "car + public transport" intermodal routes, the duration displayed on the overview page is inconsistent with the detailed route information. For example, "Bike+Public Transport" in the overview may show a duration of **2h 3min**, while the detailed route indicates a significantly shorter travel time.

---

**Steps to reproduce:**

1. Perform a route search. e.g.: https://dev.stadtnavi.eu/reiseplan/Hoffeld%2C%20%20Stuttgart%3A%3A48.7353%2C9.1795/Seel%C3%A4nderplatz%2C%2071083%20Herrenberg%3A%3A48.59787125%2C8.868604125708654?setTime=true&time=1733927400
3. See time in overview.
4. Select the "Bike+Public Transport" or "car + PT"  intermodal route option.
5. Compare the total duration displayed on the overview page with the duration in the detailed route view.---

**Observed behavior:**

The total duration shown on the overview page is longer than the actual travel time in the detailed route breakdown.

**Expected behavior:**

The total duration displayed on the overview page should match the detailed route's travel time, ensuring consistency and accurate information for the user.

---

**Screenshots Dev Server:**
Image

Image

**Screenshots Prod Server:*
Image

https://herrenberg.stadtnavi.de/reiseplan/Hoffeld%2C%20%20Stuttgart%3A%3A48.7353%2C9.1795/Seel%C3%A4nderplatz%2C%2071083%20Herrenberg%3A%3A48.59787125%2C8.868604125708654?setTime=true&time=1733927400

---

**Environment of the Test:**

- **Browser:** Edge

### PR DESCRIPTION
**Pull request by andreashelms**
closes #845

### CODE REVIEW

File: app/component/ItineraryPage.js [hunk 1]
```diff
@@ -324,7 +329,7 @@ class ItineraryPage extends React.Component {
             scooterRentAndPublicPlan: result.scooterRentAndPublicPlan,
             carPlan: result.carPlan,
             carRentalPlan: result.carRentalPlan,
-            parkRidePlan: result.parkRidePlan,
+            parkRidePlan,
```
Comment (hbruch) [inline app/component/ItineraryPage.js:332]: What is the reason result.parkRidePlan is not needed here?

Comment (andreashelms) [reply app/component/ItineraryPage.js:332]:
````
    const parkRidePlan = {
          ...result.parkRidePlan,
          itineraries: transitItineraries(result.parkRidePlan.itineraries),
        };
````

`result.parkRidePlan` is used, I applied a `transitItineraries` filter a few lines above.

**Review by hbruch — APPROVED** [review]
LGTM, thanks
