### PR TITLE
fix(itinerary-details): map focus buttons not working

### LINKED ISSUE #849: Bug: "Show on map" button not functioning for some transport modes and in turn-by-turn details (web)
**Description:**

In some transport modes, pressing the **"Show on map"** button does not trigger any action. Similarly, in the **detail view** of turn-by-turn directions, clicking the **"Show on map"** icon does not display the corresponding segment on the map.  

The expected behavior is for the map to focus the specific section of the route. To see the intended functionality, a route in the stadtnaviapp or the Digitransit instance can be used as a reference: https://opas.matka.fi/reitti/Piitie%201%2C%20Vantaa%3A%3A60.291831728250386%2C24.987936615943912/Olari%2C%20Espoo%3A%3A60.170374%2C24.728761/bikeAndVehicle/0?locale=en&time=1733997446

Edit: also in the live-version of stadtnavi this did not seem to be an issue:
https://herrenberg.stadtnavi.de/reiseplan/Klosterhof%2C%20Bronngasse%2013%2C%2071083%20Herrenberg%3A%3A48.5957302%2C8.868744/Stuttgart%20Hauptbahnhof%2C%20Stuttgart%3A%3A48.7856099%2C9.1833959/bikeAndVehicle/1?mapMode=bicycle&time=1734029988

---

**Steps to reproduce:**

1. Perform a route search with any transport mode, e.g.: https://dev.stadtnavi.eu/reiseplan/Charlottenplatz%2C%2070173%20Stuttgart%3A%3A48.7757704%2C9.1831419/Stuttgart%20Hauptbahnhof%2C%20Stuttgart%3A%3A48.7856099%2C9.1833959/walk?setTime=true&time=1733924700
2. Open the detail view for the route or turn-by-turn directions.
3. Press the **"Show on map"** button for any segment.
4. Observe that the map does not update or display the specific section.
5. Test the "show on map" button everywhere where it is displayed and see where it is working and where it is not working.

---

**Observed behavior:**

- For some transport modes, pressing **"Show on map"** does not update the map view.  
- In the turn-by-turn details, clicking the **"Show on map"** icon has no effect.  

**Expected behavior:**

The map should focus on and highlight the specific route section or turn corresponding to the selected detail.

---

**Screenshots:**

_Attach screenshot provided by the user._
Image
Image

**Environment:**

- **Browser:** Edge

---

**Additional information:**

Improving this functionality will align user expectations and enhance navigation usability. For reference, observe how this feature operates correctly in the Digitransit instance.

### PR DESCRIPTION
**Pull request by andreashelms**
closes #849

### CODE REVIEW

File: app/component/ItineraryPage.js [hunk 1]
```diff
@@ -774,6 +774,15 @@ class ItineraryPage extends React.Component {
...
 
+  focusToStep = (lat, lon) => {
+    this.setState({
+      bounds: [
+        [lat, lon],
+        [lat, lon],
+      ],
+    });
+  };
+
```
Comment (hbruch) [inline app/component/ItineraryPage.js]: In which way focusToStep differs from focusToPoint?

Comment (andreashelms) [reply app/component/ItineraryPage.js]: You are right, it's basically the same. I will remove that function.

**Review by hbruch — APPROVED** [review]
LGTM, thanks
