### PR TITLE
fix(map-layers): stop layers shown even if disabled

### LINKED ISSUE #790: Bug: The public transit stops are always displayed, even if they are hidden in the filter (web)
The deactivated signs appear when e.g. when changing other filters and moving the map
image

### LINKED ISSUE #883: Bus layers are show even if not intended

### PR DESCRIPTION
**Pull request by andreashelms**
closes #883
closes #790

### CODE REVIEW

File: app/util/mapLayerUtils.js [hunk 1]
```diff
@@ -146,17 +146,7 @@ export const getMapLayerOptions = (options = {}) => {
...
-      Object.keys(layerOptions[key]).forEach(subKey => {
-        if (layerOptions[key][subKey]) {
-          layerOptions[key][subKey].isLocked = true;
-          layerOptions[key][subKey].isSelected =
-            selectedMapLayers.includes(subKey) ||
-            selectedMapLayers.includes(key);
-        }
-      });
-    } else if (layerOptions.stop[key] && allModes.includes(key)) {
+    if (layerOptions.stop[key] && allModes.includes(key)) {
```
Comment (andreashelms) [inline app/util/mapLayerUtils.js]: I am not sure whether the `lockedMapLayers` are needed for StadtNavi at all or if the could removed from code  completely.

Comment (hbruch) [reply app/util/mapLayerUtils.js]: We should not remove upstream functionality. Could you introduce a config variable like "enableLockedMapLayers" (with default = true if unset)

**Review by hbruch — CHANGES_REQUESTED** [review]
Could you have a look at the comment, please?

**Review by hbruch — APPROVED** [review]
LGTM
