### PR TITLE
Fix: Sharing POIs hidden if route is displayed

### LINKED ISSUE #692: Car, bike & cargo bike sharing icons disappear when entering a route
When the user enters an origin, the car, bike & bike sharing icons are displayed normally on the map. However, after entering the destination the disappear from the map. (See Screenshots)

image
image

### PR DESCRIPTION
**Pull request by andreashelms**
## Proposed Changes

  - Always show Sharing POIs

image

## Pull Request Check List

  - A reasonable set of unit tests is included
  - Console does not show new warnings/errors
  - Changes are documented or they are self explanatory
  - This pull request does not have any merge conflicts
  - All existing tests pass in CI build
  - Code coverage does not decrease (unless measured incorrectly)

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform
  - Check that the implementation matches the design, when such one is defined in a Jira issue
  - Merge the pull request

closes #692

### CODE REVIEW

File: app/component/SummaryPage.js [hunk 1]
```diff
@@ -2653,7 +2653,7 @@ const SummaryPageWithStores = connectToStores(
   ['MapLayerStore'],
   ({ getStore }) => ({
     mapLayers: getStore('MapLayerStore').getMapLayers({
-      notThese: ['stop', 'citybike', 'vehicles'],
+      notThese: ['stop', 'vehicles'],
```
Comment (andreashelms) [inline app/component/SummaryPage.js:2656]: @leonardehrenfried  Looks like stops and vehicles (Bus positions) are also hidden if a route is displayed on the map. Is this the intended behavior?

Comment (leonardehrenfried) [reply app/component/SummaryPage.js:2656]: It seems so but to be honest I haven't been able to figure out what the logic or overarching vision is behind switching these on or off.

Comment (andreashelms) [reply app/component/SummaryPage.js:2656]: Ok. The issue only asked for fixing missing sharing pois, so I fixed that. Tell me if you think we should also show stop and vehicle markers on the map, if a route is displayed.

Comment (MartinH-open) [reply app/component/SummaryPage.js:2656]: my 2ct comment on this: 
1. it would be useful to display intermediate (bus) stops on the displayed route as smaller circles (milestones) on the way to the end of that modal route (where the current bigger circle is displayed already). 
2. I consider carpooling meeting points (P&M stops) as "sharing POIs" too. Not sure if this is implemented this way.
