### PR TITLE
fix(transit-leg): disruption view not showing on alert click

### LINKED ISSUE #904: Long alert texts within routes cannot be fully read
**Description:**  

Currently, in the alerts within the routes, **longer texts** are cut off and cannot be read in their entirety. Clicking on the arrow (intended to expand the alert) does not produce the expected result of showing the full text.  

---

**Steps to reproduce:**  

1. Open a route with alerts with long alerts in Stadtnavi. To find a stop with a long alert you can check this link:
https://[data.mfdz.de/vvs_gtfsrt_alerts_herrenberg/body.txt](https://data.mfdz.de/vvs_gtfsrt_alerts_herrenberg/body.txt)
2. Look at the alert box within the route.  
3. Observe the truncated text.  
4. Click the arrow and check if the full text appears/ or a new page with the text.  

---

**Observed behavior:**  

- Long alert texts are truncated and cannot be fully read.  
- Clicking the arrow does not expand the text but open a new page which is not related to the alert.  

---

**Screenshots/Examples:**  

Image  

---

Please check what the green arrow is supposed to do.

### PR DESCRIPTION
**Pull request by andreashelms**
closes #904

### CODE REVIEW

File: app/component/TransitLeg.js [hunk 1]
```diff
@@ -527,14 +527,12 @@ class TransitLeg extends React.Component {
...
-                      leg.trip &&
-                      `/${PREFIX_ROUTES}/${leg.route.gtfsId}/${PREFIX_DISRUPTION}/${leg.trip.pattern.code}`) ||
-                    (alert.stop && alert.stop.gtfsId
+                    // eslint-disable-next-line no-nested-ternary
+                    leg?.route?.gtfsId && leg?.trip?.pattern?.code
+                      ? `/${PREFIX_ROUTES}/${leg.route.gtfsId}/${PREFIX_DISRUPTION}/${leg.trip.pattern.code}`
+                      : alert?.stop?.gtfsId
                       ? `/${PREFIX_STOPS}/${alert.stop.gtfsId}/${PREFIX_DISRUPTION}/`
-                      : '')
+                      : ''
```
Comment (andreashelms) [inline app/component/TransitLeg.js:535]: I found no better solution for handling this.

**Review by hbruch — APPROVED** [review]
LGTM, thanks
