### PR TITLE
Fix: Wrong itinerary shown on details map

### LINKED ISSUE #482: Wrong itinerary shown on detail map
## Steps to reproduce

1. Plan any route, for example [Herrenberg to Nufringen](https://dev.stadtnavi.eu/reiseplan/Herrenberg%3A%3A48.595557%2C8.8674715/Nufringen%3A%3A48.6224388%2C8.8881021?time=1621496688)
2. Click on one of the first route to open the detail view
3. Observe that the cycling-only route is displayed on the map
Screenshot from 2021-05-20 09-45-41

### PR DESCRIPTION
**Pull request by andreashelms**
## Proposed Changes

  - Correct itinerary selected when showing route details
  
  
image

## Review

  - Read and verify the code changes
  - Test the functionality by running the UI locally with all popular browsers available in your platform

closes #482

### CODE REVIEW

File: app/component/SummaryPage.js [hunk 1]
```diff
@@ -1679,14 +1679,11 @@ class SummaryPage extends React.Component {
       return null;
     }
     let filteredItineraries;
-    if (!detailView) {
```
Comment (andreashelms) [inline app/component/SummaryPage.js:1682]: I can't think of any reason why this filter was only applied, when detailView was not selected. I leaving out the filter, itinerary indices get messed up.

**Comment by leonardehrenfried** [comment]
Thanks a lot - this is great!
